import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react"
import { onAuthStateChanged } from "firebase/auth"
import { auth } from "../services/firebase"
import { getUserAccessProfile } from "../services/accessControl"

export const LANGUAGE_STORAGE_KEY = "zenithLanguage"

export const LANGUAGE_OPTIONS = [
  { value: "pt-BR", label: "Português", shortLabel: "PT" },
  { value: "en", label: "English", shortLabel: "EN" },
  { value: "es", label: "Español", shortLabel: "ES" },
]

const SUPPORTED_LANGUAGES = new Set(LANGUAGE_OPTIONS.map((option) => option.value))

const messages = {
  "pt-BR": {
    "common.notInformed": "Não informado",
    "common.select": "Selecione",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.saving": "Salvando...",
    "common.loadingAccess": "Carregando acesso...",
    "common.farm": "fazenda",
    "common.farms": "fazendas",
    "common.hectares": "hectares",
    "common.years": "anos",
    "menu.home": "Início",
    "menu.team": "Equipe",
    "menu.add": "Adicionar",
    "menu.explore": "Explore",
    "menu.profile": "Perfil",
    "menu.tasks": "Tarefas",
    "menu.teamActions": "Ações da equipe",
    "menu.newEmployee": "Novo funcionário",
    "menu.newTask": "Nova tarefa",
    "menu.configureDrone": "Configurar drone",
    "header.hello": "Olá,",
    "header.farmer": "Agricultor",
    "header.registerFarm": "Cadastre sua fazenda",
    "header.notifications": "Notificações",
    "header.notificationCenter": "Central de notificações",
    "header.closeNotifications": "Fechar notificações",
    "header.updates": "atualizações",
    "header.openProfile": "Abrir perfil",
    "header.enableAlerts": "Ativar alertas do navegador",
    "header.alertsEnabled": "Notificações ativadas com sucesso.",
    "header.pendingFarm": "Cadastro da fazenda pendente",
    "header.pendingFarmDescription": "Cadastre sua fazenda para liberar clima, área e monitoramento.",
    "header.registerNow": "Cadastrar agora",
    "header.firstStep": "Primeiro passo",
    "header.firstStepDescription": "Depois do cadastro, o painel passa a mostrar dados do campo em tempo real.",
    "header.systemOnline": "Sistema online",
    "header.monitoringFarm": "Monitoramento ativo para {{farm}}.",
    "header.monitoringYourFarm": "Monitoramento ativo para sua fazenda.",
    "header.fieldActivities": "Atividades do campo",
    "header.fieldActivitiesDescription": "Revise tarefas, diagnósticos e registros recentes.",
    "header.viewActivities": "Ver atividades",
    "profile.quickActions": "Ações rápidas do perfil",
    "profile.edit": "Editar perfil",
    "profile.changePassword": "Alterar senha",
    "profile.sending": "Enviando...",
    "profile.roleAdmin": "Conta administradora",
    "profile.roleEmployee": "Conta de funcionário",
    "profile.roleCollaborator": "Conta de colaborador",
    "profile.personalAccount": "Conta pessoal",
    "profile.farmer": "Agricultor",
    "profile.propertySummary": "Resumo da propriedade",
    "profile.property": "Propriedade",
    "profile.locationMissing": "Localização não informada",
    "profile.summary": "Resumo",
    "profile.settings": "Configurações",
    "profile.personalInfo": "Informações pessoais",
    "profile.personalInfoDescription": "Seus dados e preferências da conta",
    "profile.farm": "Fazenda",
    "profile.farmDescription": "Consulte os dados da propriedade",
    "profile.editDescription": "Atualize suas informações",
    "profile.saveChanges": "Salvar alterações",
    "profile.logout": "Sair",
    "profile.logoutDescription": "Encerrar sessão nesta conta",
    "profile.language": "Idioma",
    "profile.languageDescription": "Escolha o idioma do aplicativo",
    "profile.languageGroup": "Idiomas disponíveis",
    "profile.languageUpdated": "Idioma atualizado com sucesso!",
    "profile.languageDeviceUpdated": "Idioma alterado neste dispositivo.",
    "profile.languageError": "Não foi possível atualizar o idioma.",
    "profile.updated": "Perfil atualizado com sucesso! 🌱",
    "profile.updateError": "Erro ao atualizar perfil",
    "profile.loadError": "Erro ao carregar perfil",
    "profile.farmLoadError": "Erro ao carregar dados da fazenda",
    "profile.farmUpdated": "Fazenda atualizada com sucesso! 🌱",
    "profile.farmUpdateError": "Erro ao atualizar fazenda",
    "profile.teamManaged": "Dados da equipe devem ser alterados pelo administrador.",
    "profile.passwordSent": "Enviamos um link para alterar sua senha no e-mail cadastrado.",
    "profile.passwordError": "Não foi possível enviar o link para alterar a senha.",
    "profile.lessThanDay": "menos de um dia",
    "profile.oneDay": "1 dia",
    "profile.days": "{{count}} dias",
    "profile.oneMonth": "1 mês",
    "profile.months": "{{count}} meses",
    "profile.oneYear": "1 ano",
    "profile.yearsCount": "{{count}} anos",
    "personal.name": "Nome completo",
    "personal.email": "E-mail",
    "personal.phone": "Telefone",
    "personal.location": "Localização",
    "personal.role": "Função",
    "personal.admin": "Produtor / Gestor",
    "personal.employee": "Funcionário",
    "personal.collaborator": "Colaborador",
    "personal.nameMissing": "Nome não informado",
    "personal.verified": "Conta verificada",
    "personal.unverified": "E-mail não verificado",
    "personal.security": "Segurança",
    "personal.sendingEmail": "Enviando e-mail...",
    "editor.chooseIcon": "Escolha seu ícone",
    "editor.age": "Idade",
    "editor.totalHectares": "Hectares totais",
    "editor.city": "Cidade",
    "editor.state": "UF",
    "editor.note": "Estas informações serão usadas como padrão para novas propriedades",
    "farm.none": "Nenhuma fazenda cadastrada",
    "farm.noneDescription": "Cadastre sua primeira fazenda para começar a monitorar suas safras",
    "farm.register": "Cadastrar Fazenda",
    "farm.name": "Nome",
    "farm.nameField": "Nome da Fazenda",
    "farm.totalArea": "Área total",
    "farm.crop": "Cultura",
    "farm.district": "Bairro/Distrito",
    "farm.postalCode": "CEP",
    "farm.acquisition": "Aquisição",
    "farm.acquisitionDate": "Data de aquisição",
    "farm.relationship": "Vínculo",
    "farm.ownerType": "Tipo de proprietário",
    "farm.fallbackName": "Fazenda",
    "farm.edit": "Editar Fazenda",
    "farm.neighborhood": "Bairro",
    "farm.city": "Município",
    "farm.newPhone": "Novo telefone",
    "farm.searchingPostalCode": "Buscando CEP...",
    "farm.owner": "Proprietário",
    "farm.tenant": "Arrendatário",
    "farm.partner": "Parceiro",
    "farm.borrower": "Comodatário",
    "farm.others": "Outros",
    "farm.postalNotFound": "CEP não encontrado",
    "farm.postalLookupError": "Não foi possível buscar o CEP",
    "farm.nameRequired": "Nome da fazenda é obrigatório",
    "farm.areaRequired": "Área total é obrigatória",
    "farm.areaPositive": "Área deve ser um número positivo",
    "farm.cityRequired": "Município é obrigatório",
    "farm.stateRequired": "UF é obrigatória",
    "farm.stateAbbreviation": "Use apenas a sigla (ex: SP)",
    "home.currentWeather": "Clima atual",
    "home.myFarm": "Minha fazenda",
    "home.locationMissing": "Local não cadastrado",
    "home.quickSummary": "Resumo rápido",
    "home.lastFlight": "Último voo",
    "home.cropHealth": "Saúde da lavoura",
    "home.alerts": "Alertas",
    "home.noRecord": "Sem registro",
    "home.noImage": "Nenhuma imagem analisada",
    "home.atTime": "às {{time}}",
    "home.awaiting": "Aguardando",
    "home.registerFarmShort": "Cadastre a fazenda",
    "home.noAnalysis": "Sem análise",
    "home.makeDiagnosis": "Faça um diagnóstico",
    "home.inconclusive": "Inconclusivo",
    "home.repeatAnalysis": "Repita a análise",
    "home.good": "Boa",
    "home.confidence": "{{value}}% de confiança",
    "home.attention": "Atenção",
    "home.noData": "Sem dados",
    "home.noAlerts": "Nenhum alerta",
    "home.allGood": "Tudo em ordem",
    "home.alert": "alerta",
    "home.alertPlural": "alertas",
    "home.overdueActivity": "atividade atrasada",
    "home.overdueActivities": "atividades atrasadas",
    "home.soil": "Solo",
    "home.humidity": "Umidade",
    "home.wind": "Vento",
    "home.precipitation": "Precipitação",
    "home.downloadApp": "Baixar aplicativo",
    "home.installZenith": "Instale o Zenith neste celular",
    "home.teamDashboard": "Dashboard da Equipe",
    "home.teamDashboardDescription": "Monitore funcionários, tarefas, horários e produtividade.",
    "home.recentActivities": "Atividades Recentes",
    "home.viewAll": "Ver todas",
    "home.startMonitoring": "Iniciar Monitoramento",
    "activities.none": "Nenhuma atividade registrada",
    "activities.noneDescription": "Cadastre uma fazenda para começar a monitorar suas atividades em tempo real",
    "activities.registerFarm": "Cadastrar Fazenda",
    "activities.field": "Atividades do Campo",
    "activities.manageTasks": "Gerencie suas tarefas",
    "activities.fieldDescription": "Visualize e gerencie todas as atividades da sua fazenda",
    "activities.pendingTasks": "Tarefas pendentes",
    "activities.clickAccess": "Clique para acessar",
    "activities.recentDiagnostics": "Diagnósticos Recentes",
    "activities.savedDiagnostics": "{{count}} diagnósticos salvos",
    "activities.clickViewAll": "Clique para ver todos",
    "activities.mappingFlight": "Voo de Mapeamento",
    "activities.twoHoursAgo": "2h atrás",
    "activities.mappingDescription": "Visualize áreas mapeadas no mapa interativo",
    "activities.viewMap": "Ver no mapa",
    "modules.title": "Módulos do Sistema",
    "modules.diagnosis": "Diagnóstico",
    "modules.diagnosisDescription": "Análise de plantas",
    "modules.weather": "Clima",
    "modules.weatherDescription": "Previsão 7 dias",
    "modules.monitoring": "Monitoramento",
    "modules.monitoringDescription": "Análise do plantio",
    "modules.diary": "Diário",
    "modules.diaryDescription": "Registros da plantação",
    "modules.map": "Mapa",
    "modules.mapDescription": "Visualização 3D",
    "modules.stock": "Estoque",
    "modules.stockDescription": "Insumos e materiais",
    "modules.activities": "Atividades",
    "modules.activitiesDescription": "Tarefas do campo",
    "modules.legislation": "Legislação",
    "explore.modules": "Módulos de exploração",
    "explore.multispectral": "Análise multiespectral",
    "explore.multispectralDescription": "Este recurso avançado está disponível exclusivamente no aplicativo Zenith para desktop.",
    "footer.description": "Tecnologia de ponta para agricultura de precisão, monitoramento em tempo real e análise de dados.",
    "footer.platform": "Plataforma",
    "footer.dashboard": "Dashboard",
    "footer.farms": "Fazendas",
    "footer.flights": "Voos",
    "footer.reports": "Relatórios",
    "footer.support": "Suporte",
    "footer.help": "Ajuda",
    "footer.documentation": "Documentação",
    "footer.tutorials": "Tutoriais",
    "footer.contact": "Contato",
    "footer.status": "Status",
    "footer.legal": "Legal",
    "footer.terms": "Termos",
    "footer.privacy": "Privacidade",
    "footer.security": "Segurança",
    "footer.licenses": "Licenças",
    "footer.institutionalSupport": "Apoio institucional",
    "footer.monitoredFarms": "🌱 2.500+ fazendas monitoradas",
    "footer.completedFlights": "🚁 15.000+ voos realizados",
    "footer.processedAnalyses": "📊 1M+ análises processadas",
    "footer.rights": "© 2026 Zenith. Todos os direitos reservados.",
    "footer.version": "Versão 2.0.1 • Desenvolvido com agricultura de precisão",
    "footer.brandTagline": "Sua precisão agrícola no ponto mais alto",
    "footer.navigation": "Navegação",
    "footer.talkToZenith": "Fale com a Zenith",
    "footer.phone": "Telefone",
    "footer.email": "E-mail",
    "footer.instagram": "Instagram",
    "footer.aiScreening": "Triagem IA",
    "footer.monitoring": "Monitoramento",
    "footer.management": "Gestão",
    "footer.projectOrigin": "Origem do projeto",
    "footer.projectTitle": "TCC desenvolvido por estudantes da Etec Polivalente de Americana",
    "footer.projectDescription": "Da formação técnica à construção de uma agtech.",
    "footer.fieldTechnology": "Tecnologia aplicada ao campo com clareza e precisão.",
    "climate.tomorrow": "Amanhã",
    "climate.dailyForecast": "Previsão do dia",
    "climate.noFarm": "Nenhuma fazenda cadastrada",
    "climate.incompleteLocation": "Localização da fazenda incompleta",
    "climate.noConnection": "Sem conexão com o serviço de clima",
    "climate.fetchError": "Erro ao buscar clima",
    "climate.searching": "Buscando clima",
    "climate.fetchingFor": "Obtendo dados para {{city}}...",
    "climate.loading": "Carregando...",
    "climate.errorTitle": "Ops!",
    "climate.noData": "Não foi possível obter os dados",
    "climate.retry": "Tentar novamente",
    "climate.degreesCelsius": "{{value}} graus Celsius",
    "climate.minimum": "Mínima",
    "climate.maximum": "Máxima",
    "climate.metrics": "Métricas meteorológicas",
    "climate.today": "Hoje",
    "climate.details": "Detalhes meteorológicos",
    "climate.pressure": "Pressão",
    "climate.rain1h": "Chuva (1h)",
    "climate.gust": "Rajada",
    "climate.visibility": "Visibilidade",
    "climate.clouds": "Nuvens",
    "climate.sunrise": "Nascer do sol",
    "climate.sunset": "Pôr do sol",
    "climate.apiUpdated": "Atualizado API",
    "climate.nextDays": "Próximos dias",
    "climate.planningForecast": "Previsão diária para planejamento",
    "climate.forecastUnavailable": "Previsão dos próximos dias indisponível no momento.",
    "climate.recommendations": "Recomendações",
    "climate.hide": "Ocultar",
    "climate.viewDetails": "Ver detalhes",
    "climate.updatedAt": "atualizado às {{time}}",
    "climate.drySoil": "Solo seco",
    "climate.irrigationRecommended": "Irrigação recomendada",
    "climate.highHumidity": "Alta umidade",
    "climate.fungusRisk": "Risco de fungos. Monitore as plantas",
    "climate.intenseHeat": "Calor intenso",
    "climate.protectFromSun": "Proteja plantas sensíveis do sol forte",
    "climate.lowTemperature": "Temperatura baixa",
    "climate.frostRisk": "Risco de geada. Proteja as plantas",
    "climate.strongWind": "Vento forte",
    "climate.avoidSpraying": "Evite pulverização e verifique estruturas",
    "climate.heavyRain": "Chuva forte",
    "climate.checkDrainage": "Suspenda irrigação e verifique drenagem",
    "climate.idealConditions": "Condições ideais",
    "climate.perfectForField": "Perfeito para atividades no campo",
    "climate.stableWeather": "Clima estável",
    "climate.normalConditions": "Condições normais para as atividades agrícolas",
    "climate.humidityRainDetails": "Umidade atual de {{humidity}}% e chuva de {{rain}} mm na última hora.",
    "climate.temperatureDetails": "Temperatura atual de {{temperature}}°C, com sensação de {{feelsLike}}°C.",
    "climate.windDetails": "Vento atual de {{wind}} m/s, com rajadas de {{gust}} m/s.",
    "climate.rainDetails": "Volume registrado de {{rain}} mm na última hora.",
    "climate.generalDetails": "Temperatura de {{temperature}}°C, umidade de {{humidity}}% e vento de {{wind}} m/s.",
    "diagnosis.title": "Diagnóstico",
    "diagnosis.subtitle": "Identifique doenças em plantas com",
    "diagnosis.ai": "inteligência artificial.",
    "diagnosis.summary": "Resumo dos diagnósticos",
    "diagnosis.diagnoses": "Diagnósticos",
    "diagnosis.thisMonth": "{{count}} neste mês",
    "diagnosis.averageConfidence": "Confiança média",
    "diagnosis.previousMonth": "comparado ao mês anterior",
    "diagnosis.activity": "Atividade",
    "diagnosis.lastMonths": "últimos 6 meses",
    "diagnosis.chartLabel": "Quantidade de diagnósticos nos últimos seis meses",
    "diagnosis.attention": "Atenção",
    "diagnosis.takePhoto": "Tirar foto",
    "diagnosis.captureNow": "Capture uma imagem agora",
    "diagnosis.gallery": "Galeria",
    "diagnosis.chooseImages": "Escolha até 100 imagens",
    "diagnosis.history": "Histórico de diagnósticos",
    "diagnosis.viewAll": "Ver todos",
    "diagnosis.noneYet": "Nenhum diagnóstico ainda",
    "diagnosis.firstDiagnosis": "Realize seu primeiro diagnóstico tirando uma foto ou selecionando da galeria",
    "diagnosis.photos": "{{count}} fotos",
    "diagnosis.showMore": "Ver mais",
    "diagnosis.tip": "Dica",
    "diagnosis.tipText": "Fotografe a folha com boa iluminação e mantenha a câmera estável para melhor resultado",
    "diagnosis.soyLeaves": "Folhas de soja no campo",
    "diagnosis.takeAnother": "Tirar outra foto",
    "diagnosis.addPhotos": "Adicionar fotos",
    "diagnosis.takePhotoShort": "Tirar foto",
    "diagnosis.add": "Adicionar",
    "diagnosis.again": "novamente",
    "diagnosis.moreImages": "mais imagens",
    "diagnosis.cameraError": "Não foi possível acessar a câmera. Verifique a permissão do navegador ou selecione fotos da galeria.",
    "diagnosis.batchError": "Não foi possível analisar o lote agora. Verifique a conexão e tente novamente.",
    "diagnosis.inconclusiveBatch": "Lote inconclusivo",
    "diagnosis.detectedConditions": "{{count}} condições detectadas",
    "diagnosis.artificialIntelligence": "Inteligência artificial",
    "diagnosis.processing": "Processando",
    "diagnosis.analyzingImages": "Analisando {{count}} imagens",
    "diagnosis.analyzingImage": "Analisando imagem",
    "diagnosis.batchProcessing": "Consolidando o levantamento e identificando padrões com inteligência artificial.",
    "diagnosis.imageProcessing": "Processando a imagem e preparando o diagnóstico com inteligência artificial.",
    "diagnosis.inProgress": "Análise em andamento",
    "diagnosis.preprocessing": "Pré-processamento",
    "diagnosis.imagePreparation": "Preparação da imagem",
    "diagnosis.inference": "Inferência",
    "diagnosis.aiReading": "Leitura pela IA",
    "diagnosis.consolidation": "Consolidação",
    "diagnosis.finalResult": "Resultado final",
    "diagnosis.resultGeneration": "Geração do diagnóstico",
    "diagnosis.automaticResult": "O resultado aparecerá automaticamente quando o processamento for concluído.",
  },
  en: {
    "common.notInformed": "Not provided",
    "common.select": "Select",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.loadingAccess": "Loading access...",
    "common.farm": "farm",
    "common.farms": "farms",
    "common.hectares": "hectares",
    "common.years": "years",
    "menu.home": "Home",
    "menu.team": "Team",
    "menu.add": "Add",
    "menu.explore": "Explore",
    "menu.profile": "Profile",
    "menu.tasks": "Tasks",
    "menu.teamActions": "Team actions",
    "menu.newEmployee": "New employee",
    "menu.newTask": "New task",
    "menu.configureDrone": "Configure drone",
    "header.hello": "Hello,",
    "header.farmer": "Farmer",
    "header.registerFarm": "Register your farm",
    "header.notifications": "Notifications",
    "header.notificationCenter": "Notification center",
    "header.closeNotifications": "Close notifications",
    "header.updates": "updates",
    "header.openProfile": "Open profile",
    "header.enableAlerts": "Enable browser alerts",
    "header.alertsEnabled": "Notifications enabled successfully.",
    "header.pendingFarm": "Farm registration pending",
    "header.pendingFarmDescription": "Register your farm to unlock weather, area, and monitoring.",
    "header.registerNow": "Register now",
    "header.firstStep": "First step",
    "header.firstStepDescription": "After registration, the dashboard will show real-time field data.",
    "header.systemOnline": "System online",
    "header.monitoringFarm": "Monitoring active for {{farm}}.",
    "header.monitoringYourFarm": "Monitoring active for your farm.",
    "header.fieldActivities": "Field activities",
    "header.fieldActivitiesDescription": "Review tasks, diagnoses, and recent records.",
    "header.viewActivities": "View activities",
    "profile.quickActions": "Profile quick actions",
    "profile.edit": "Edit profile",
    "profile.changePassword": "Change password",
    "profile.sending": "Sending...",
    "profile.roleAdmin": "Administrator account",
    "profile.roleEmployee": "Employee account",
    "profile.roleCollaborator": "Collaborator account",
    "profile.personalAccount": "Personal account",
    "profile.farmer": "Farmer",
    "profile.propertySummary": "Property summary",
    "profile.property": "Property",
    "profile.locationMissing": "Location not provided",
    "profile.summary": "Summary",
    "profile.settings": "Settings",
    "profile.personalInfo": "Personal information",
    "profile.personalInfoDescription": "Your account details and preferences",
    "profile.farm": "Farm",
    "profile.farmDescription": "View property details",
    "profile.editDescription": "Update your information",
    "profile.saveChanges": "Save changes",
    "profile.logout": "Log out",
    "profile.logoutDescription": "End this account session",
    "profile.language": "Language",
    "profile.languageDescription": "Choose the application language",
    "profile.languageGroup": "Available languages",
    "profile.languageUpdated": "Language updated successfully!",
    "profile.languageDeviceUpdated": "Language changed on this device.",
    "profile.languageError": "The language could not be updated.",
    "profile.updated": "Profile updated successfully! 🌱",
    "profile.updateError": "Error updating profile",
    "profile.loadError": "Error loading profile",
    "profile.farmLoadError": "Error loading farm data",
    "profile.farmUpdated": "Farm updated successfully! 🌱",
    "profile.farmUpdateError": "Error updating farm",
    "profile.teamManaged": "Team data must be changed by the administrator.",
    "profile.passwordSent": "We sent a password reset link to your registered email.",
    "profile.passwordError": "The password reset link could not be sent.",
    "profile.lessThanDay": "less than a day",
    "profile.oneDay": "1 day",
    "profile.days": "{{count}} days",
    "profile.oneMonth": "1 month",
    "profile.months": "{{count}} months",
    "profile.oneYear": "1 year",
    "profile.yearsCount": "{{count}} years",
    "personal.name": "Full name",
    "personal.email": "Email",
    "personal.phone": "Phone",
    "personal.location": "Location",
    "personal.role": "Role",
    "personal.admin": "Producer / Manager",
    "personal.employee": "Employee",
    "personal.collaborator": "Collaborator",
    "personal.nameMissing": "Name not provided",
    "personal.verified": "Verified account",
    "personal.unverified": "Email not verified",
    "personal.security": "Security",
    "personal.sendingEmail": "Sending email...",
    "editor.chooseIcon": "Choose your icon",
    "editor.age": "Age",
    "editor.totalHectares": "Total hectares",
    "editor.city": "City",
    "editor.state": "State",
    "editor.note": "This information will be used as the default for new properties",
    "farm.none": "No farm registered",
    "farm.noneDescription": "Register your first farm to start monitoring your crops",
    "farm.register": "Register Farm",
    "farm.name": "Name",
    "farm.nameField": "Farm Name",
    "farm.totalArea": "Total area",
    "farm.crop": "Crop",
    "farm.district": "Neighborhood/District",
    "farm.postalCode": "Postal code",
    "farm.acquisition": "Acquisition",
    "farm.acquisitionDate": "Acquisition date",
    "farm.relationship": "Relationship",
    "farm.ownerType": "Owner type",
    "farm.fallbackName": "Farm",
    "farm.edit": "Edit Farm",
    "farm.neighborhood": "Neighborhood",
    "farm.city": "City",
    "farm.newPhone": "New phone",
    "farm.searchingPostalCode": "Searching postal code...",
    "farm.owner": "Owner",
    "farm.tenant": "Tenant",
    "farm.partner": "Partner",
    "farm.borrower": "Borrower",
    "farm.others": "Others",
    "farm.postalNotFound": "Postal code not found",
    "farm.postalLookupError": "The postal code could not be searched",
    "farm.nameRequired": "Farm name is required",
    "farm.areaRequired": "Total area is required",
    "farm.areaPositive": "Area must be a positive number",
    "farm.cityRequired": "City is required",
    "farm.stateRequired": "State is required",
    "farm.stateAbbreviation": "Use only the abbreviation (e.g. SP)",
    "home.currentWeather": "Current weather",
    "home.myFarm": "My farm",
    "home.locationMissing": "Location not registered",
    "home.quickSummary": "Quick summary",
    "home.lastFlight": "Last flight",
    "home.cropHealth": "Crop health",
    "home.alerts": "Alerts",
    "home.noRecord": "No record",
    "home.noImage": "No image analyzed",
    "home.atTime": "at {{time}}",
    "home.awaiting": "Waiting",
    "home.registerFarmShort": "Register the farm",
    "home.noAnalysis": "No analysis",
    "home.makeDiagnosis": "Run a diagnosis",
    "home.inconclusive": "Inconclusive",
    "home.repeatAnalysis": "Repeat the analysis",
    "home.good": "Good",
    "home.confidence": "{{value}}% confidence",
    "home.attention": "Attention",
    "home.noData": "No data",
    "home.noAlerts": "No alerts",
    "home.allGood": "Everything is fine",
    "home.alert": "alert",
    "home.alertPlural": "alerts",
    "home.overdueActivity": "overdue activity",
    "home.overdueActivities": "overdue activities",
    "home.soil": "Soil",
    "home.humidity": "Humidity",
    "home.wind": "Wind",
    "home.precipitation": "Precipitation",
    "home.downloadApp": "Download application",
    "home.installZenith": "Install Zenith on this phone",
    "home.teamDashboard": "Team Dashboard",
    "home.teamDashboardDescription": "Monitor employees, tasks, schedules, and productivity.",
    "home.recentActivities": "Recent Activities",
    "home.viewAll": "View all",
    "home.startMonitoring": "Start Monitoring",
    "activities.none": "No activities recorded",
    "activities.noneDescription": "Register a farm to start monitoring activities in real time",
    "activities.registerFarm": "Register Farm",
    "activities.field": "Field Activities",
    "activities.manageTasks": "Manage your tasks",
    "activities.fieldDescription": "View and manage all your farm activities",
    "activities.pendingTasks": "Pending tasks",
    "activities.clickAccess": "Click to access",
    "activities.recentDiagnostics": "Recent Diagnoses",
    "activities.savedDiagnostics": "{{count}} saved diagnoses",
    "activities.clickViewAll": "Click to view all",
    "activities.mappingFlight": "Mapping Flight",
    "activities.twoHoursAgo": "2h ago",
    "activities.mappingDescription": "View mapped areas on the interactive map",
    "activities.viewMap": "View on map",
    "modules.title": "System Modules",
    "modules.diagnosis": "Diagnosis",
    "modules.diagnosisDescription": "Plant analysis",
    "modules.weather": "Weather",
    "modules.weatherDescription": "7-day forecast",
    "modules.monitoring": "Monitoring",
    "modules.monitoringDescription": "Planting analysis",
    "modules.diary": "Diary",
    "modules.diaryDescription": "Crop records",
    "modules.map": "Map",
    "modules.mapDescription": "3D visualization",
    "modules.stock": "Inventory",
    "modules.stockDescription": "Inputs and materials",
    "modules.activities": "Activities",
    "modules.activitiesDescription": "Field tasks",
    "modules.legislation": "Legislation",
    "explore.modules": "Explore modules",
    "explore.multispectral": "Multispectral analysis",
    "explore.multispectralDescription": "This advanced feature is available exclusively in the Zenith desktop application.",
    "footer.description": "Advanced technology for precision agriculture, real-time monitoring, and data analysis.",
    "footer.platform": "Platform",
    "footer.dashboard": "Dashboard",
    "footer.farms": "Farms",
    "footer.flights": "Flights",
    "footer.reports": "Reports",
    "footer.support": "Support",
    "footer.help": "Help",
    "footer.documentation": "Documentation",
    "footer.tutorials": "Tutorials",
    "footer.contact": "Contact",
    "footer.status": "Status",
    "footer.legal": "Legal",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",
    "footer.security": "Security",
    "footer.licenses": "Licenses",
    "footer.institutionalSupport": "Institutional support",
    "footer.monitoredFarms": "🌱 2,500+ monitored farms",
    "footer.completedFlights": "🚁 15,000+ completed flights",
    "footer.processedAnalyses": "📊 1M+ processed analyses",
    "footer.rights": "© 2026 Zenith. All rights reserved.",
    "footer.version": "Version 2.0.1 • Developed with precision agriculture",
    "footer.brandTagline": "Agricultural precision at its highest point",
    "footer.navigation": "Navigation",
    "footer.talkToZenith": "Contact Zenith",
    "footer.phone": "Phone",
    "footer.email": "Email",
    "footer.instagram": "Instagram",
    "footer.aiScreening": "AI Screening",
    "footer.monitoring": "Monitoring",
    "footer.management": "Management",
    "footer.projectOrigin": "Project origin",
    "footer.projectTitle": "Final project developed by students from Etec Polivalente de Americana",
    "footer.projectDescription": "From technical education to building an agtech.",
    "footer.fieldTechnology": "Technology applied to the field with clarity and precision.",
    "climate.tomorrow": "Tomorrow",
    "climate.dailyForecast": "Daily forecast",
    "climate.noFarm": "No farm registered",
    "climate.incompleteLocation": "Farm location is incomplete",
    "climate.noConnection": "No connection to the weather service",
    "climate.fetchError": "Error fetching weather",
    "climate.searching": "Checking weather",
    "climate.fetchingFor": "Getting data for {{city}}...",
    "climate.loading": "Loading...",
    "climate.errorTitle": "Oops!",
    "climate.noData": "Weather data could not be retrieved",
    "climate.retry": "Try again",
    "climate.degreesCelsius": "{{value}} degrees Celsius",
    "climate.minimum": "Minimum",
    "climate.maximum": "Maximum",
    "climate.metrics": "Weather metrics",
    "climate.today": "Today",
    "climate.details": "Weather details",
    "climate.pressure": "Pressure",
    "climate.rain1h": "Rain (1h)",
    "climate.gust": "Gust",
    "climate.visibility": "Visibility",
    "climate.clouds": "Clouds",
    "climate.sunrise": "Sunrise",
    "climate.sunset": "Sunset",
    "climate.apiUpdated": "API updated",
    "climate.nextDays": "Next days",
    "climate.planningForecast": "Daily forecast for planning",
    "climate.forecastUnavailable": "The forecast for the next few days is currently unavailable.",
    "climate.recommendations": "Recommendations",
    "climate.hide": "Hide",
    "climate.viewDetails": "View details",
    "climate.updatedAt": "updated at {{time}}",
    "climate.drySoil": "Dry soil",
    "climate.irrigationRecommended": "Irrigation recommended",
    "climate.highHumidity": "High humidity",
    "climate.fungusRisk": "Risk of fungus. Monitor the plants",
    "climate.intenseHeat": "Intense heat",
    "climate.protectFromSun": "Protect sensitive plants from strong sunlight",
    "climate.lowTemperature": "Low temperature",
    "climate.frostRisk": "Risk of frost. Protect the plants",
    "climate.strongWind": "Strong wind",
    "climate.avoidSpraying": "Avoid spraying and check structures",
    "climate.heavyRain": "Heavy rain",
    "climate.checkDrainage": "Stop irrigation and check drainage",
    "climate.idealConditions": "Ideal conditions",
    "climate.perfectForField": "Perfect for field activities",
    "climate.stableWeather": "Stable weather",
    "climate.normalConditions": "Normal conditions for agricultural activities",
    "climate.humidityRainDetails": "Current humidity is {{humidity}}% with {{rain}} mm of rain in the last hour.",
    "climate.temperatureDetails": "Current temperature is {{temperature}}°C and feels like {{feelsLike}}°C.",
    "climate.windDetails": "Current wind is {{wind}} m/s, with gusts of {{gust}} m/s.",
    "climate.rainDetails": "{{rain}} mm recorded in the last hour.",
    "climate.generalDetails": "Temperature {{temperature}}°C, humidity {{humidity}}%, and wind {{wind}} m/s.",
    "diagnosis.title": "Diagnosis",
    "diagnosis.subtitle": "Identify plant diseases with",
    "diagnosis.ai": "artificial intelligence.",
    "diagnosis.summary": "Diagnosis summary",
    "diagnosis.diagnoses": "Diagnoses",
    "diagnosis.thisMonth": "{{count}} this month",
    "diagnosis.averageConfidence": "Average confidence",
    "diagnosis.previousMonth": "compared with the previous month",
    "diagnosis.activity": "Activity",
    "diagnosis.lastMonths": "last 6 months",
    "diagnosis.chartLabel": "Number of diagnoses in the last six months",
    "diagnosis.attention": "Attention",
    "diagnosis.takePhoto": "Take photo",
    "diagnosis.captureNow": "Capture an image now",
    "diagnosis.gallery": "Gallery",
    "diagnosis.chooseImages": "Choose up to 100 images",
    "diagnosis.history": "Diagnosis history",
    "diagnosis.viewAll": "View all",
    "diagnosis.noneYet": "No diagnoses yet",
    "diagnosis.firstDiagnosis": "Run your first diagnosis by taking a photo or selecting images from the gallery",
    "diagnosis.photos": "{{count}} photos",
    "diagnosis.showMore": "Show more",
    "diagnosis.tip": "Tip",
    "diagnosis.tipText": "Photograph the leaf in good light and keep the camera steady for a better result",
    "diagnosis.soyLeaves": "Soybean leaves in the field",
    "diagnosis.takeAnother": "Take another photo",
    "diagnosis.addPhotos": "Add photos",
    "diagnosis.takePhotoShort": "Take photo",
    "diagnosis.add": "Add",
    "diagnosis.again": "again",
    "diagnosis.moreImages": "more images",
    "diagnosis.cameraError": "The camera could not be accessed. Check browser permission or select photos from the gallery.",
    "diagnosis.batchError": "The batch could not be analyzed now. Check your connection and try again.",
    "diagnosis.inconclusiveBatch": "Inconclusive batch",
    "diagnosis.detectedConditions": "{{count}} conditions detected",
    "diagnosis.artificialIntelligence": "Artificial intelligence",
    "diagnosis.processing": "Processing",
    "diagnosis.analyzingImages": "Analyzing {{count}} images",
    "diagnosis.analyzingImage": "Analyzing image",
    "diagnosis.batchProcessing": "Consolidating the survey and identifying patterns with artificial intelligence.",
    "diagnosis.imageProcessing": "Processing the image and preparing the diagnosis with artificial intelligence.",
    "diagnosis.inProgress": "Analysis in progress",
    "diagnosis.preprocessing": "Preprocessing",
    "diagnosis.imagePreparation": "Image preparation",
    "diagnosis.inference": "Inference",
    "diagnosis.aiReading": "AI reading",
    "diagnosis.consolidation": "Consolidation",
    "diagnosis.finalResult": "Final result",
    "diagnosis.resultGeneration": "Diagnosis generation",
    "diagnosis.automaticResult": "The result will appear automatically when processing is complete.",
  },
  es: {
    "common.notInformed": "No informado",
    "common.select": "Seleccione",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.saving": "Guardando...",
    "common.loadingAccess": "Cargando acceso...",
    "common.farm": "finca",
    "common.farms": "fincas",
    "common.hectares": "hectáreas",
    "common.years": "años",
    "menu.home": "Inicio",
    "menu.team": "Equipo",
    "menu.add": "Añadir",
    "menu.explore": "Explorar",
    "menu.profile": "Perfil",
    "menu.tasks": "Tareas",
    "menu.teamActions": "Acciones del equipo",
    "menu.newEmployee": "Nuevo empleado",
    "menu.newTask": "Nueva tarea",
    "menu.configureDrone": "Configurar dron",
    "header.hello": "Hola,",
    "header.farmer": "Agricultor",
    "header.registerFarm": "Registre su finca",
    "header.notifications": "Notificaciones",
    "header.notificationCenter": "Centro de notificaciones",
    "header.closeNotifications": "Cerrar notificaciones",
    "header.updates": "actualizaciones",
    "header.openProfile": "Abrir perfil",
    "header.enableAlerts": "Activar alertas del navegador",
    "header.alertsEnabled": "Notificaciones activadas correctamente.",
    "header.pendingFarm": "Registro de la finca pendiente",
    "header.pendingFarmDescription": "Registre su finca para habilitar clima, área y monitoreo.",
    "header.registerNow": "Registrar ahora",
    "header.firstStep": "Primer paso",
    "header.firstStepDescription": "Después del registro, el panel mostrará datos del campo en tiempo real.",
    "header.systemOnline": "Sistema en línea",
    "header.monitoringFarm": "Monitoreo activo para {{farm}}.",
    "header.monitoringYourFarm": "Monitoreo activo para su finca.",
    "header.fieldActivities": "Actividades del campo",
    "header.fieldActivitiesDescription": "Revise tareas, diagnósticos y registros recientes.",
    "header.viewActivities": "Ver actividades",
    "profile.quickActions": "Acciones rápidas del perfil",
    "profile.edit": "Editar perfil",
    "profile.changePassword": "Cambiar contraseña",
    "profile.sending": "Enviando...",
    "profile.roleAdmin": "Cuenta administradora",
    "profile.roleEmployee": "Cuenta de empleado",
    "profile.roleCollaborator": "Cuenta de colaborador",
    "profile.personalAccount": "Cuenta personal",
    "profile.farmer": "Agricultor",
    "profile.propertySummary": "Resumen de la propiedad",
    "profile.property": "Propiedad",
    "profile.locationMissing": "Ubicación no informada",
    "profile.summary": "Resumen",
    "profile.settings": "Configuración",
    "profile.personalInfo": "Información personal",
    "profile.personalInfoDescription": "Sus datos y preferencias de la cuenta",
    "profile.farm": "Finca",
    "profile.farmDescription": "Consulte los datos de la propiedad",
    "profile.editDescription": "Actualice su información",
    "profile.saveChanges": "Guardar cambios",
    "profile.logout": "Salir",
    "profile.logoutDescription": "Cerrar la sesión de esta cuenta",
    "profile.language": "Idioma",
    "profile.languageDescription": "Elija el idioma de la aplicación",
    "profile.languageGroup": "Idiomas disponibles",
    "profile.languageUpdated": "¡Idioma actualizado correctamente!",
    "profile.languageDeviceUpdated": "Idioma cambiado en este dispositivo.",
    "profile.languageError": "No se pudo actualizar el idioma.",
    "profile.updated": "¡Perfil actualizado correctamente! 🌱",
    "profile.updateError": "Error al actualizar el perfil",
    "profile.loadError": "Error al cargar el perfil",
    "profile.farmLoadError": "Error al cargar los datos de la finca",
    "profile.farmUpdated": "¡Finca actualizada correctamente! 🌱",
    "profile.farmUpdateError": "Error al actualizar la finca",
    "profile.teamManaged": "Los datos del equipo deben ser modificados por el administrador.",
    "profile.passwordSent": "Enviamos un enlace para cambiar su contraseña al correo registrado.",
    "profile.passwordError": "No se pudo enviar el enlace para cambiar la contraseña.",
    "profile.lessThanDay": "menos de un día",
    "profile.oneDay": "1 día",
    "profile.days": "{{count}} días",
    "profile.oneMonth": "1 mes",
    "profile.months": "{{count}} meses",
    "profile.oneYear": "1 año",
    "profile.yearsCount": "{{count}} años",
    "personal.name": "Nombre completo",
    "personal.email": "Correo electrónico",
    "personal.phone": "Teléfono",
    "personal.location": "Ubicación",
    "personal.role": "Función",
    "personal.admin": "Productor / Gestor",
    "personal.employee": "Empleado",
    "personal.collaborator": "Colaborador",
    "personal.nameMissing": "Nombre no informado",
    "personal.verified": "Cuenta verificada",
    "personal.unverified": "Correo no verificado",
    "personal.security": "Seguridad",
    "personal.sendingEmail": "Enviando correo...",
    "editor.chooseIcon": "Elija su icono",
    "editor.age": "Edad",
    "editor.totalHectares": "Hectáreas totales",
    "editor.city": "Ciudad",
    "editor.state": "Estado",
    "editor.note": "Esta información se utilizará como predeterminada para nuevas propiedades",
    "farm.none": "Ninguna finca registrada",
    "farm.noneDescription": "Registre su primera finca para comenzar a supervisar sus cultivos",
    "farm.register": "Registrar Finca",
    "farm.name": "Nombre",
    "farm.nameField": "Nombre de la Finca",
    "farm.totalArea": "Área total",
    "farm.crop": "Cultivo",
    "farm.district": "Barrio/Distrito",
    "farm.postalCode": "Código postal",
    "farm.acquisition": "Adquisición",
    "farm.acquisitionDate": "Fecha de adquisición",
    "farm.relationship": "Vínculo",
    "farm.ownerType": "Tipo de propietario",
    "farm.fallbackName": "Finca",
    "farm.edit": "Editar Finca",
    "farm.neighborhood": "Barrio",
    "farm.city": "Municipio",
    "farm.newPhone": "Nuevo teléfono",
    "farm.searchingPostalCode": "Buscando código postal...",
    "farm.owner": "Propietario",
    "farm.tenant": "Arrendatario",
    "farm.partner": "Socio",
    "farm.borrower": "Comodatario",
    "farm.others": "Otros",
    "farm.postalNotFound": "Código postal no encontrado",
    "farm.postalLookupError": "No se pudo buscar el código postal",
    "farm.nameRequired": "El nombre de la finca es obligatorio",
    "farm.areaRequired": "El área total es obligatoria",
    "farm.areaPositive": "El área debe ser un número positivo",
    "farm.cityRequired": "El municipio es obligatorio",
    "farm.stateRequired": "El estado es obligatorio",
    "farm.stateAbbreviation": "Use solo la abreviatura (ej.: SP)",
    "home.currentWeather": "Clima actual",
    "home.myFarm": "Mi finca",
    "home.locationMissing": "Ubicación no registrada",
    "home.quickSummary": "Resumen rápido",
    "home.lastFlight": "Último vuelo",
    "home.cropHealth": "Salud del cultivo",
    "home.alerts": "Alertas",
    "home.noRecord": "Sin registro",
    "home.noImage": "Ninguna imagen analizada",
    "home.atTime": "a las {{time}}",
    "home.awaiting": "Esperando",
    "home.registerFarmShort": "Registre la finca",
    "home.noAnalysis": "Sin análisis",
    "home.makeDiagnosis": "Realice un diagnóstico",
    "home.inconclusive": "No concluyente",
    "home.repeatAnalysis": "Repita el análisis",
    "home.good": "Buena",
    "home.confidence": "{{value}}% de confianza",
    "home.attention": "Atención",
    "home.noData": "Sin datos",
    "home.noAlerts": "Sin alertas",
    "home.allGood": "Todo en orden",
    "home.alert": "alerta",
    "home.alertPlural": "alertas",
    "home.overdueActivity": "actividad atrasada",
    "home.overdueActivities": "actividades atrasadas",
    "home.soil": "Suelo",
    "home.humidity": "Humedad",
    "home.wind": "Viento",
    "home.precipitation": "Precipitación",
    "home.downloadApp": "Descargar aplicación",
    "home.installZenith": "Instale Zenith en este teléfono",
    "home.teamDashboard": "Panel del Equipo",
    "home.teamDashboardDescription": "Supervise empleados, tareas, horarios y productividad.",
    "home.recentActivities": "Actividades Recientes",
    "home.viewAll": "Ver todas",
    "home.startMonitoring": "Iniciar Monitoreo",
    "activities.none": "No hay actividades registradas",
    "activities.noneDescription": "Registre una finca para comenzar a supervisar actividades en tiempo real",
    "activities.registerFarm": "Registrar Finca",
    "activities.field": "Actividades del Campo",
    "activities.manageTasks": "Gestione sus tareas",
    "activities.fieldDescription": "Vea y gestione todas las actividades de su finca",
    "activities.pendingTasks": "Tareas pendientes",
    "activities.clickAccess": "Pulse para acceder",
    "activities.recentDiagnostics": "Diagnósticos Recientes",
    "activities.savedDiagnostics": "{{count}} diagnósticos guardados",
    "activities.clickViewAll": "Pulse para ver todos",
    "activities.mappingFlight": "Vuelo de Mapeo",
    "activities.twoHoursAgo": "hace 2 h",
    "activities.mappingDescription": "Vea las áreas mapeadas en el mapa interactivo",
    "activities.viewMap": "Ver en el mapa",
    "modules.title": "Módulos del Sistema",
    "modules.diagnosis": "Diagnóstico",
    "modules.diagnosisDescription": "Análisis de plantas",
    "modules.weather": "Clima",
    "modules.weatherDescription": "Pronóstico de 7 días",
    "modules.monitoring": "Monitoreo",
    "modules.monitoringDescription": "Análisis de la siembra",
    "modules.diary": "Diario",
    "modules.diaryDescription": "Registros del cultivo",
    "modules.map": "Mapa",
    "modules.mapDescription": "Visualización 3D",
    "modules.stock": "Inventario",
    "modules.stockDescription": "Insumos y materiales",
    "modules.activities": "Actividades",
    "modules.activitiesDescription": "Tareas del campo",
    "modules.legislation": "Legislación",
    "explore.modules": "Módulos de exploración",
    "explore.multispectral": "Análisis multiespectral",
    "explore.multispectralDescription": "Esta función avanzada está disponible exclusivamente en la aplicación de escritorio Zenith.",
    "footer.description": "Tecnología avanzada para agricultura de precisión, monitoreo en tiempo real y análisis de datos.",
    "footer.platform": "Plataforma",
    "footer.dashboard": "Panel",
    "footer.farms": "Fincas",
    "footer.flights": "Vuelos",
    "footer.reports": "Informes",
    "footer.support": "Soporte",
    "footer.help": "Ayuda",
    "footer.documentation": "Documentación",
    "footer.tutorials": "Tutoriales",
    "footer.contact": "Contacto",
    "footer.status": "Estado",
    "footer.legal": "Legal",
    "footer.terms": "Términos",
    "footer.privacy": "Privacidad",
    "footer.security": "Seguridad",
    "footer.licenses": "Licencias",
    "footer.institutionalSupport": "Apoyo institucional",
    "footer.monitoredFarms": "🌱 Más de 2.500 fincas monitoreadas",
    "footer.completedFlights": "🚁 Más de 15.000 vuelos realizados",
    "footer.processedAnalyses": "📊 Más de 1M de análisis procesados",
    "footer.rights": "© 2026 Zenith. Todos los derechos reservados.",
    "footer.version": "Versión 2.0.1 • Desarrollado con agricultura de precisión",
    "footer.brandTagline": "Su precisión agrícola en el punto más alto",
    "footer.navigation": "Navegación",
    "footer.talkToZenith": "Hable con Zenith",
    "footer.phone": "Teléfono",
    "footer.email": "Correo electrónico",
    "footer.instagram": "Instagram",
    "footer.aiScreening": "Evaluación con IA",
    "footer.monitoring": "Monitoreo",
    "footer.management": "Gestión",
    "footer.projectOrigin": "Origen del proyecto",
    "footer.projectTitle": "Proyecto final desarrollado por estudiantes de Etec Polivalente de Americana",
    "footer.projectDescription": "De la formación técnica a la creación de una agtech.",
    "footer.fieldTechnology": "Tecnología aplicada al campo con claridad y precisión.",
    "climate.tomorrow": "Mañana",
    "climate.dailyForecast": "Pronóstico del día",
    "climate.noFarm": "Ninguna finca registrada",
    "climate.incompleteLocation": "La ubicación de la finca está incompleta",
    "climate.noConnection": "Sin conexión con el servicio meteorológico",
    "climate.fetchError": "Error al consultar el clima",
    "climate.searching": "Consultando el clima",
    "climate.fetchingFor": "Obteniendo datos para {{city}}...",
    "climate.loading": "Cargando...",
    "climate.errorTitle": "¡Ups!",
    "climate.noData": "No se pudieron obtener los datos",
    "climate.retry": "Intentar de nuevo",
    "climate.degreesCelsius": "{{value}} grados Celsius",
    "climate.minimum": "Mínima",
    "climate.maximum": "Máxima",
    "climate.metrics": "Métricas meteorológicas",
    "climate.today": "Hoy",
    "climate.details": "Detalles meteorológicos",
    "climate.pressure": "Presión",
    "climate.rain1h": "Lluvia (1h)",
    "climate.gust": "Ráfaga",
    "climate.visibility": "Visibilidad",
    "climate.clouds": "Nubes",
    "climate.sunrise": "Amanecer",
    "climate.sunset": "Atardecer",
    "climate.apiUpdated": "API actualizada",
    "climate.nextDays": "Próximos días",
    "climate.planningForecast": "Pronóstico diario para planificación",
    "climate.forecastUnavailable": "El pronóstico de los próximos días no está disponible en este momento.",
    "climate.recommendations": "Recomendaciones",
    "climate.hide": "Ocultar",
    "climate.viewDetails": "Ver detalles",
    "climate.updatedAt": "actualizado a las {{time}}",
    "climate.drySoil": "Suelo seco",
    "climate.irrigationRecommended": "Riego recomendado",
    "climate.highHumidity": "Humedad alta",
    "climate.fungusRisk": "Riesgo de hongos. Supervise las plantas",
    "climate.intenseHeat": "Calor intenso",
    "climate.protectFromSun": "Proteja las plantas sensibles del sol fuerte",
    "climate.lowTemperature": "Temperatura baja",
    "climate.frostRisk": "Riesgo de heladas. Proteja las plantas",
    "climate.strongWind": "Viento fuerte",
    "climate.avoidSpraying": "Evite fumigar y revise las estructuras",
    "climate.heavyRain": "Lluvia intensa",
    "climate.checkDrainage": "Suspenda el riego y revise el drenaje",
    "climate.idealConditions": "Condiciones ideales",
    "climate.perfectForField": "Perfecto para actividades de campo",
    "climate.stableWeather": "Clima estable",
    "climate.normalConditions": "Condiciones normales para las actividades agrícolas",
    "climate.humidityRainDetails": "Humedad actual del {{humidity}}% y lluvia de {{rain}} mm en la última hora.",
    "climate.temperatureDetails": "Temperatura actual de {{temperature}}°C, con sensación de {{feelsLike}}°C.",
    "climate.windDetails": "Viento actual de {{wind}} m/s, con ráfagas de {{gust}} m/s.",
    "climate.rainDetails": "Volumen registrado de {{rain}} mm en la última hora.",
    "climate.generalDetails": "Temperatura de {{temperature}}°C, humedad del {{humidity}}% y viento de {{wind}} m/s.",
    "diagnosis.title": "Diagnóstico",
    "diagnosis.subtitle": "Identifique enfermedades en plantas con",
    "diagnosis.ai": "inteligencia artificial.",
    "diagnosis.summary": "Resumen de diagnósticos",
    "diagnosis.diagnoses": "Diagnósticos",
    "diagnosis.thisMonth": "{{count}} este mes",
    "diagnosis.averageConfidence": "Confianza media",
    "diagnosis.previousMonth": "comparado con el mes anterior",
    "diagnosis.activity": "Actividad",
    "diagnosis.lastMonths": "últimos 6 meses",
    "diagnosis.chartLabel": "Cantidad de diagnósticos en los últimos seis meses",
    "diagnosis.attention": "Atención",
    "diagnosis.takePhoto": "Tomar foto",
    "diagnosis.captureNow": "Capture una imagen ahora",
    "diagnosis.gallery": "Galería",
    "diagnosis.chooseImages": "Elija hasta 100 imágenes",
    "diagnosis.history": "Historial de diagnósticos",
    "diagnosis.viewAll": "Ver todos",
    "diagnosis.noneYet": "Aún no hay diagnósticos",
    "diagnosis.firstDiagnosis": "Realice su primer diagnóstico tomando una foto o seleccionando imágenes de la galería",
    "diagnosis.photos": "{{count}} fotos",
    "diagnosis.showMore": "Ver más",
    "diagnosis.tip": "Consejo",
    "diagnosis.tipText": "Fotografíe la hoja con buena iluminación y mantenga la cámara estable para obtener un mejor resultado",
    "diagnosis.soyLeaves": "Hojas de soja en el campo",
    "diagnosis.takeAnother": "Tomar otra foto",
    "diagnosis.addPhotos": "Añadir fotos",
    "diagnosis.takePhotoShort": "Tomar foto",
    "diagnosis.add": "Añadir",
    "diagnosis.again": "nuevamente",
    "diagnosis.moreImages": "más imágenes",
    "diagnosis.cameraError": "No se pudo acceder a la cámara. Verifique el permiso del navegador o seleccione fotos de la galería.",
    "diagnosis.batchError": "No se pudo analizar el lote ahora. Verifique la conexión e inténtelo de nuevo.",
    "diagnosis.inconclusiveBatch": "Lote no concluyente",
    "diagnosis.detectedConditions": "{{count}} condiciones detectadas",
    "diagnosis.artificialIntelligence": "Inteligencia artificial",
    "diagnosis.processing": "Procesando",
    "diagnosis.analyzingImages": "Analizando {{count}} imágenes",
    "diagnosis.analyzingImage": "Analizando imagen",
    "diagnosis.batchProcessing": "Consolidando el relevamiento e identificando patrones con inteligencia artificial.",
    "diagnosis.imageProcessing": "Procesando la imagen y preparando el diagnóstico con inteligencia artificial.",
    "diagnosis.inProgress": "Análisis en curso",
    "diagnosis.preprocessing": "Preprocesamiento",
    "diagnosis.imagePreparation": "Preparación de la imagen",
    "diagnosis.inference": "Inferencia",
    "diagnosis.aiReading": "Lectura por IA",
    "diagnosis.consolidation": "Consolidación",
    "diagnosis.finalResult": "Resultado final",
    "diagnosis.resultGeneration": "Generación del diagnóstico",
    "diagnosis.automaticResult": "El resultado aparecerá automáticamente cuando finalice el procesamiento.",
  },
}

const LanguageContext = createContext(null)

const getUserLanguageStorageKey = (userId) => `${LANGUAGE_STORAGE_KEY}:${userId}`

export function normalizeLanguage(language) {
  if (SUPPORTED_LANGUAGES.has(language)) return language
  if (String(language || "").toLowerCase().startsWith("en")) return "en"
  if (String(language || "").toLowerCase().startsWith("es")) return "es"
  return "pt-BR"
}

export function translate(language, key, variables = {}) {
  const normalizedLanguage = normalizeLanguage(language)
  const template = messages[normalizedLanguage]?.[key] ?? messages["pt-BR"]?.[key] ?? key

  return Object.entries(variables).reduce(
    (text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)),
    template
  )
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => (
    normalizeLanguage(localStorage.getItem(LANGUAGE_STORAGE_KEY))
  ))

  const setLanguage = useCallback((nextLanguage) => {
    const normalizedLanguage = normalizeLanguage(nextLanguage)
    localStorage.setItem(LANGUAGE_STORAGE_KEY, normalizedLanguage)
    if (auth.currentUser?.uid) {
      localStorage.setItem(getUserLanguageStorageKey(auth.currentUser.uid), normalizedLanguage)
    }
    auth.languageCode = normalizedLanguage === "pt-BR" ? "pt" : normalizedLanguage
    document.documentElement.lang = normalizedLanguage
    setLanguageState(normalizedLanguage)
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (currentUser) => {
      if (!currentUser) return

      try {
        const profile = await getUserAccessProfile(currentUser.uid)
        const deviceLanguage = localStorage.getItem(getUserLanguageStorageKey(currentUser.uid))
        if (profile || deviceLanguage) {
          setLanguage(deviceLanguage || profile?.language || "pt-BR")
        }
      } catch (error) {
        console.error("Erro ao carregar idioma do perfil:", error)
      }
    })

    return () => unsubscribe()
  }, [setLanguage])

  const t = useCallback(
    (key, variables) => translate(language, key, variables),
    [language]
  )

  const value = useMemo(() => ({
    language,
    locale: language,
    setLanguage,
    t,
  }), [language, setLanguage, t])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage deve ser usado dentro de LanguageProvider")
  return context
}
